### ISSUE TITLE
Configured time before expiration alert will show.

### ISSUE THREAD

**Issue by shnela** [swappsco/django-plans#6]
Now expiration alert from `expiration_messages.html` appears 14 days before account expire.
This parameter should be configured in settings.

**Comment by cdvv7788** [comment]
Agree with this. Users of the app should have the freedom to configure the application as much as possible.
@shnela Can you send a pull request for this?

**Comment by rdlabspl** [comment]
@cdvv7788 Pull request's been created.

**Comment by cdvv7788** [comment]
https://github.com/swappsco/django-plans/pull/10 I added a code review. Please check it.
